apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podyam
    enviroment: emilio 
  name: podyam
spec:
  containers:
  - image: emilio
    name: podyam
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

