apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rabbitmq
    enviroment: emilio 
  name: rabbitmq
spec:
  containers:
  - image: rabbitmq
    name: rabbitmq
    volumeMounts:
      - mountPath: "/scratch"
        name: my-volume
    resources: {}
  volumes:
    - name: my-volume
      emptyDir:
        sizeLimit: 50Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}